site_name: pyforecast Documentation
repo_url: https://github.com/PlayitLOUD73/pyforecast/
copyright: 2022 - Luke Welborn
nav:
  - Home: index.md
  - Installation: install.md
  - Basic Usage: usage.md
  - About: about.md
theme: readthedocs
